[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
source = "backend"
healthcheckPath = "/health"

[services.variables]
FLASK_ENV = "production"
PORT = "5000"

[[services]]
name = "frontend"
source = "frontend"
healthcheckPath = "/health"

[services.variables]
REACT_APP_API_URL = "${{backend.RAILWAY_PUBLIC_URL}}"